### ISSUE TITLE
Windows Chromium Subscription Conversion Feature

### ISSUE THREAD

**Issue by PeterKW** [kodxana/Watch-on-Odysee#10]
Is the subscription conversion feature still working? Struggling to get the csv file that I got from Google working:

Go to https://takeout.google.com/settings/takeout
Deselect everything except YouTube and YouTube Music and within that only select subscriptions
Go through the process and create the export
Once it's exported, open the archive and find YouTube and YouTube Music/subscriptions/subscriptions.json and upload it to the extension

**Comment by kodxana** [comment]
Fixed in https://github.com/kodxana/Watch-on-Odysee/pull/11

**Comment by PeterKW** [comment]
Thank you very much. Do you know what the version number to look out for will be when this is released? 

![image](https://user-images.githubusercontent.com/13779157/132112471-1669f210-0ccc-4a87-a4d4-dc24844b0520.png)
