### ISSUE TITLE
Subscription convert don't work - Wrong file format

### ISSUE THREAD

**Issue by BKeyport** [kodxana/Watch-on-Odysee#15]
**Describe the bug**
Can't use subscription converter due to Google changing formats

**To Reproduce**
1. Attempt to use subscription convert
2. Follow directions on extension's webpage
3. Youtube directory no longer has JSON, it's now CSV

**Expected behavior**
Able to convert subscriptions

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Edge
 - Version Current. Don't know how to check

**Comment by ghost** [comment]
OMG YES newpipe already implemented it and mow i want odysee to do it too

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY
