### ISSUE TITLE
Extension doesn't work anymore?

### ISSUE THREAD

**Issue by jguez** [kodxana/Watch-on-Odysee#16]
I'm on Brave, I uninstalled and reinstalled the extension but it doesn't seem to work anymore. Even if I turn it off, the button doesn't pop up on youtube. Did Youtube break it?

**Comment by neilunger** [comment]
+1 but on Firefox instead of Brave

**Comment by yadomi** [comment]
Do you have any errors in the console from the extension ? (On Youtube.com, Right click > Inspect, then refresh the page)

**Comment by WolfIcefang** [comment]
I just switched over from Windows to Kubuntu Linux. The extension has stopped working for me as well.
Here is a screenshot of the carnage. 
![image](https://user-images.githubusercontent.com/38160450/148259335-174f1dfe-6b8c-40d3-9d5b-5af2deebbd94.png)
On the left is the inspect window for the YouTube page, on the right is the debug inspect tool for the Watch on LBRY Extension. The console for YouTube spat out a ton of content not visible in the screenshot, but there were no red lines, only some yellow warning lines.
I seem to get the same (or very similar) output to both consoles whether I'm set to redirect to the app, to odysee, or to Madiator.com
Let me know if you need me to copy any text, expand any dropdown menus, etc. I don't know much about debugging.

Watch on LBRY is Version 1.7.5, last updated December 26, 2021.
Firefox is version 95.0.1 (64-bit).
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-22-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: AMD RENOIR

**Comment by kodxana** [comment]
This is wrong repo :)
https://github.com/LBRYFoundation/Watch-on-LBRY
