### ISSUE TITLE
Subscription convertor not working - CSV is the default now rather than JSON

### ISSUE THREAD

**Issue by f0rkth1s** [kodxana/Watch-on-Odysee#18]
**Describe the bug**
The subscription converter no longer works but did previously.

**To Reproduce**
Export CSV of subscriptions from Google Takeout, convert to JSON.
Attempt to import via plugin, nothing happens.

**Expected behavior**
Should produce a list of matched channels on odysee.

**Desktop (please complete the following information):**
 - Browser - Firefox, Brave & Chrome

**Additional context**
It might be handy to have an example json export that is in a known good configuration so we could convert the csv to json correctly.

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY
