### ISSUE TITLE
Allow us to choose between the LBRY desktop app and Odysee

### ISSUE THREAD

**Issue by erkinalp** [kodxana/Watch-on-Odysee#21]
**Is your feature request related to a problem? Please describe.**
As lbry.tv now redirects to Odysee, the extension now redirects to Odysee, and does not allow us to open the content in the desktop app.

**Describe the solution you'd like**
Allow us to choose between the LBRY desktop app and Odysee.

**Comment by kodxana** [comment]
Use https://github.com/LBRYFoundation/Watch-on-LBRY then it's more updated version with most fixes. :)
