### ISSUE TITLE
When pressing the "Watch on Odysee" button, it should pause the youtube video

### ISSUE THREAD

**Issue by w1kee** [kodxana/Watch-on-Odysee#24]
**Is your feature request related to a problem? Please describe.**
In Firefox, on a pinned youtube tab, when you press the watch on odysee button, it opens odysee in a new tab, but doesn't pause the youtube video, so it continues playing.

**Describe the solution you'd like**
1. It pauses the youtube video
2. Or it opens odysee in the pinned tab

**Describe alternatives you've considered**

**Additional context**

**Comment by nomadshiba** [comment]
Implemented https://github.com/kodxana/Watch-on-Odysee/commit/1eb21eb51fe92f2be1895b972bd2a0f8ce62c51e
