### ISSUE TITLE
Infinite odysee tabs spawning when using Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by K0SS4** [kodxana/Watch-on-Odysee#25]
**Describe the bug**
When I click on some youtube(wich is on session box "1") video(that is also on odysee(wich is on session box "2")) it starts to spawn odysee browser tabs indefinitely.

**To Reproduce**
1. Install https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
2. Set youtube.com to open in a container
3. Set odysee.com to open in a container(different one from youtube)
4. Go to some youtube video that is also on odysee(e.g. https://www.youtube.com/watch?v=4YpQSY-vo5Q)
5. See error

**Expected behavior**
Only one tab of odysee opens up

**Screenshots**
![image](https://user-images.githubusercontent.com/79310905/177982653-4ca99af8-fe1b-45be-8a18-f8ac95e6bb8c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (10.0.22000 Build 22000)
 - Browser: FIrefox
 - Version: 102.0

**Comment by nomadshiba** [comment]
Is this still an issue? 
Because I seem to not be able to reproduce it.

**Comment by K0SS4** [comment]
I don't know which commit fixed it but it seems that it's all working fine.
I'm closing the issue. Thanks
