### ISSUE TITLE
Option: Don't redirect in playlists

### ISSUE THREAD

**Issue by megaxorg** [kodxana/Watch-on-Odysee#26]
I use the Chrome extension and it works as it should.

If I want to play music or watch related contend on YouTube I often use autogenerated playlists. If 1 of 25 videos is on odysee, the plugin redirects me out of the playlist onto a single video at odysee.

I think an option to handle videos in a playlist different would be great (i.e. don't redirect, just show button).

**Comment by nomadshiba** [comment]
Good catch, gonna add the option when I can.
