### ISSUE TITLE
Not working on atleast one video

### ISSUE THREAD

**Issue by arthurmelton** [kodxana/Watch-on-Odysee#8]
**Describe the bug**
it is not redirecting to the odysee version

**To Reproduce**
1. Go to https://www.youtube.com/watch?v=rhgwIhB58PA

**Expected behavior**
go to https://odysee.com/@veritasium:f/the-biggest-myth-in-education:a

**Desktop (please complete the following information):**
 - OS: Arch, Linux
 - Browser: FireFox
 - Version: 1.7.2

**Comment by kodxana** [comment]
I checked this video on both firefox and chrome and worked fine without problems. Sorry for delayed response :)

**Comment by arthurmelton** [comment]
well it works for me too now weird but at the time it did not
